name: Publish

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm run test
  publish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Prepare
        run: |
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GH_REGISTRY_TOKEN }}
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Install Dependencies
        run: npm ci
      - name: Version Bump
        run: |
          npm run release
          git push --follow-tags origin master
      - name: Publish To GitHub
        run: |
          npm config set registry https://npm.pkg.github.com
          npm publish
      - name: Publish To NPM
        run: |
          npm config set registry https://registry.npmjs.org
          npm publish
